version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 8080:3000
    volumes:
      - ./:/code
    environment:
      - MONGO_URL=mongodb://mongo:27017/tasks
  mongo:
    image: mongo
      #  ports:
      #- 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:

